name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    env:
      MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build
      shell: cmd
      run: |
        "%MSBUILD_PATH%\MSBuild.exe" Source/Osiris.vcxproj /p:Platform=Win32 /p:Configuration=Release -m

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Osiris-${{ github.run_id }}
        path: Source/Osiris/Release/Osiris.dll
